export interface Service {
  id: string;
  title: string;
  category: string;
  description: string;
  price: string;
  deliveryTime: string;
  rating: number;
  reviews: number;
  image: string;
}

export const services: Service[] = [
  {
    id: '1',
    title: 'Content Writing',
    category: 'Digital Marketing',
    description: 'Professional content writing services for blogs, websites, and marketing materials with SEO optimization.',
    price: '₹5,000/article',
    deliveryTime: '3 days',
    rating: 4.8,
    reviews: 142,
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800',
  },
  {
    id: '2',
    title: 'SEO Optimization',
    category: 'Digital Marketing',
    description: 'Boost your website ranking with complete SEO audit, keyword research, and on-page optimization.',
    price: '₹20,000',
    deliveryTime: '15 days',
    rating: 4.9,
    reviews: 95,
    image: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800',
  },
  {
    id: '3',
    title: 'Social Media Marketing',
    category: 'Digital Marketing',
    description: 'Complete social media management for Instagram, Facebook, LinkedIn with content creation and analytics.',
    price: '₹15,000/month',
    deliveryTime: '30 days',
    rating: 4.9,
    reviews: 127,
    image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800',
  },
  {
    id: '4',
    title: 'Email Marketing',
    category: 'Digital Marketing',
    description: 'Strategic email campaigns with automation, templates, and performance tracking for maximum engagement.',
    price: '₹12,000/month',
    deliveryTime: '20 days',
    rating: 4.7,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800',
  },
  {
    id: '5',
    title: 'Brand Marketing',
    category: 'Digital Marketing',
    description: 'Complete brand marketing strategy including positioning, messaging, and multi-channel campaigns.',
    price: '₹35,000',
    deliveryTime: '30 days',
    rating: 5.0,
    reviews: 67,
    image: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=800',
  },
  {
    id: '6',
    title: 'HR Consultancy',
    category: 'Consultancy Services',
    description: 'Complete HR solutions including recruitment, training, employee management, and policy development.',
    price: '₹18,000',
    deliveryTime: '25 days',
    rating: 4.6,
    reviews: 64,
    image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800',
  },
  {
    id: '7',
    title: 'Business Consultancy',
    category: 'Consultancy Services',
    description: 'Expert business consultation for startups and enterprises with actionable growth strategies.',
    price: '₹25,000',
    deliveryTime: '20 days',
    rating: 4.9,
    reviews: 78,
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
  },
  {
    id: '8',
    title: 'Marketing Strategy',
    category: 'Consultancy Services',
    description: 'Comprehensive marketing strategy development with market analysis and actionable implementation plans.',
    price: '₹22,000',
    deliveryTime: '18 days',
    rating: 4.8,
    reviews: 53,
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
  },
  {
    id: '9',
    title: 'Process Optimization',
    category: 'Consultancy Services',
    description: 'Streamline business operations with process mapping, efficiency analysis, and automation solutions.',
    price: '₹28,000',
    deliveryTime: '25 days',
    rating: 4.7,
    reviews: 41,
    image: 'https://images.unsplash.com/photo-1553028826-f4804a6dba3b?w=800',
  },
  {
    id: '10',
    title: 'Graphic Design',
    category: 'Creative Services',
    description: 'Professional graphic design for logos, branding, social media posts, and marketing materials.',
    price: '₹8,000',
    deliveryTime: '7 days',
    rating: 5.0,
    reviews: 203,
    image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800',
  },
  {
    id: '11',
    title: 'Animation',
    category: 'Creative Services',
    description: '2D and 3D animation services for explainer videos, product demos, and brand storytelling.',
    price: '₹15,000',
    deliveryTime: '14 days',
    rating: 4.9,
    reviews: 118,
    image: 'https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=800',
  },
  {
    id: '12',
    title: 'Video Editing',
    category: 'Creative Services',
    description: 'High-quality video editing for YouTube, reels, corporate videos with color grading and effects.',
    price: '₹12,000',
    deliveryTime: '10 days',
    rating: 4.7,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800',
  },
  {
    id: '13',
    title: 'Photo Editing',
    category: 'Creative Services',
    description: 'Professional photo editing and retouching for products, portraits, and commercial photography.',
    price: '₹3,000/photo',
    deliveryTime: '2 days',
    rating: 4.8,
    reviews: 237,
    image: 'https://images.unsplash.com/photo-1618761714954-0b8cd0026356?w=800',
  },
  {
    id: '14',
    title: 'Coaching Institute Support',
    category: 'Education & Training',
    description: 'Complete support for coaching institutes including curriculum design, teacher training, and management.',
    price: '₹30,000/month',
    deliveryTime: '30 days',
    rating: 4.9,
    reviews: 45,
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800',
  },
  {
    id: '15',
    title: 'Offline Courses',
    category: 'Education & Training',
    description: 'Professional offline training courses for technical skills, soft skills, and professional development.',
    price: '₹10,000/course',
    deliveryTime: '60 days',
    rating: 4.8,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
  },
  {
    id: '16',
    title: 'Corporate Training',
    category: 'Education & Training',
    description: 'Customized corporate training programs for team development, leadership, and skill enhancement.',
    price: '₹50,000',
    deliveryTime: '30 days',
    rating: 5.0,
    reviews: 82,
    image: 'https://images.unsplash.com/photo-1560439513-74b037a25d84?w=800',
  },
  {
    id: '17',
    title: 'BPO Training & Support',
    category: 'Education & Training',
    description: 'Complete BPO training including call handling, customer support, chat support, and email management.',
    price: '₹15,000',
    deliveryTime: '20 days',
    rating: 4.7,
    reviews: 94,
    image: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800',
  },
  {
    id: '18',
    title: 'Data Entry & Chat Support',
    category: 'Education & Training',
    description: 'Training for data entry operations and professional chat support with practical hands-on experience.',
    price: '₹8,000',
    deliveryTime: '15 days',
    rating: 4.6,
    reviews: 71,
    image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800',
  },
];
